# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/pyqt/BgGui/BgGui.ui'
#
# Created: Sun Aug 28 09:43:55 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 708)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 708))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 708))
        palette = QtGui.QPalette()
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/app.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("#tab{font-size: 12pt;font-family: Arial;}\n"
"#tab_2{font-size: 12pt;font-family: Arial;}\n"
"#tab_3{font-size: 12pt;font-family: Arial;}\n"
"#tab_4{font-size: 12pt;font-family: Arial;}\n"
"#tab_5{font-size: 12pt;font-family: Arial;}\n"
"#menuBar{font-size: 12pt;font-family: Arial;}\n"
"#menuBgSerial{font-size: 10pt;font-family: Arial;}\n"
"#menuBgObjReg{font-size: 10pt;font-family: Arial;}\n"
"#menuBgVoice{font-size: 10pt;font-family: Arial;}\n"
"#menuBgGps{font-size: 10pt;font-family: Arial;}\n"
"#menuHelp{font-size: 10pt;font-family: Arial;}"))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setStyleSheet(_fromUtf8("MainWindow{border-image: url(:/0/bg.png)}"))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1002, 689))
        self.tabWidget.setMinimumSize(QtCore.QSize(1002, 689))
        self.tabWidget.setMaximumSize(QtCore.QSize(1002, 689))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.tab.setFont(font)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_9 = QtGui.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(699, 550, 271, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet(_fromUtf8("border-radius:10px;color:red;background-color:#FFFF00;font-weight:bold;\n"
""))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_6 = QtGui.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(700, 340, 80, 80))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#00FFFF;font-weight:bold;\n"
""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(790, 430, 80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet(_fromUtf8("color:white;border-radius:10px;background-color:#00FFFF;font-weight:bold;\n"
""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(710, 180, 260, 30))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 0, 201, 30))
        self.horizontalSlider.setMaximum(55)
        self.horizontalSlider.setProperty("value", 28)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 20, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 0, 20, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(30, 68, 640, 53))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet(_fromUtf8("color:white;background-color:#CCCCCC;font-size:11"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(35, 18, 24, 31))
        self.label.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/voice.png);"))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 60, 251, 101))
        self.textBrowser_2.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#CCCCCC;font-size:11"))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(65, 18, 605, 40))
        self.label_4.setMinimumSize(QtCore.QSize(605, 40))
        self.label_4.setMaximumSize(QtCore.QSize(605, 40))
        self.label_4.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/siri.gif);"))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(880, 340, 80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#00FFFF;font-weight:bold;\n"
""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_8 = QtGui.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(800, 350, 60, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#FF0000;font-weight:bold;\n"
""))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_4 = QtGui.QPushButton(self.tab)
        self.pushButton_4.setGeometry(QtCore.QRect(790, 250, 80, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#00FFFF;font-weight:bold;\n"
""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(710, 18, 251, 31))
        self.label_5.setStyleSheet(_fromUtf8("border-radius:4px;color:white;background-color:#000000;font-weight:bold;\n"
""))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.radioButton = QtGui.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(40, 50, 16, 16))
        self.radioButton.setText(_fromUtf8(""))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.playlabel = QtGui.QLabel(self.tab)
        self.playlabel.setGeometry(QtCore.QRect(30, 130, 640, 480))
        self.playlabel.setMinimumSize(QtCore.QSize(640, 480))
        self.playlabel.setMaximumSize(QtCore.QSize(640, 480))
        self.playlabel.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/player.jpg);"))
        self.playlabel.setText(_fromUtf8(""))
        self.playlabel.setObjectName(_fromUtf8("playlabel"))
        self.pButton = QtGui.QPushButton(self.tab)
        self.pButton.setGeometry(QtCore.QRect(310, 610, 31, 31))
        self.pButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pButton.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/play.png);"))
        self.pButton.setText(_fromUtf8(""))
        self.pButton.setObjectName(_fromUtf8("pButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(380, 0, 171, 41))
        self.label_10.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/beltaGo.png);"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 961, 601))
        self.groupBox.setMinimumSize(QtCore.QSize(961, 601))
        self.groupBox.setMaximumSize(QtCore.QSize(961, 601))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalScrollBar_2 = QtGui.QScrollBar(self.groupBox)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(90, 150, 371, 21))
        self.horizontalScrollBar_2.setMinimum(-10)
        self.horizontalScrollBar_2.setMaximum(10)
        self.horizontalScrollBar_2.setPageStep(2)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName(_fromUtf8("horizontalScrollBar_2"))
        self.horizontalScrollBar_3 = QtGui.QScrollBar(self.groupBox)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(90, 220, 371, 21))
        self.horizontalScrollBar_3.setMinimum(-30)
        self.horizontalScrollBar_3.setMaximum(-10)
        self.horizontalScrollBar_3.setPageStep(2)
        self.horizontalScrollBar_3.setProperty("value", -20)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName(_fromUtf8("horizontalScrollBar_3"))
        self.horizontalScrollBar_4 = QtGui.QScrollBar(self.groupBox)
        self.horizontalScrollBar_4.setGeometry(QtCore.QRect(90, 290, 371, 21))
        self.horizontalScrollBar_4.setMaximum(20)
        self.horizontalScrollBar_4.setPageStep(2)
        self.horizontalScrollBar_4.setProperty("value", 10)
        self.horizontalScrollBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_4.setObjectName(_fromUtf8("horizontalScrollBar_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 83, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 220, 83, 22))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 290, 83, 22))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 380, 161, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#FF0000;font-weight:bold;\n"
""))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 380, 161, 60))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet(_fromUtf8("border-radius:10px;color:white;background-color:#FFFF00;font-weight:bold;\n"
""))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(380, 0, 171, 41))
        self.label_7.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/beltaGo.png);"))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(380, 0, 171, 41))
        self.label_8.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/beltaGo.png);"))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 0, 991, 41))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(380, 0, 171, 41))
        self.label_9.setStyleSheet(_fromUtf8("border-image: url(:/icon/icon/beltaGo.png);"))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuBeltaGo = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.menuBeltaGo.setFont(font)
        self.menuBeltaGo.setObjectName(_fromUtf8("menuBeltaGo"))
        self.menuBgSerial = QtGui.QMenu(self.menuBar)
        self.menuBgSerial.setObjectName(_fromUtf8("menuBgSerial"))
        self.menuBgObjReg = QtGui.QMenu(self.menuBar)
        self.menuBgObjReg.setObjectName(_fromUtf8("menuBgObjReg"))
        self.menuBgVoice = QtGui.QMenu(self.menuBar)
        self.menuBgVoice.setEnabled(True)
        self.menuBgVoice.setObjectName(_fromUtf8("menuBgVoice"))
        self.menuBgGps = QtGui.QMenu(self.menuBar)
        self.menuBgGps.setObjectName(_fromUtf8("menuBgGps"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setTitle(_fromUtf8(""))
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setTitle(_fromUtf8(""))
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_3.setIcon(icon1)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menuBar)
        self.menu_4.setTitle(_fromUtf8(""))
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_5 = QtGui.QMenu(self.menuBar)
        self.menu_5.setEnabled(False)
        self.menu_5.setTitle(_fromUtf8(""))
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menuX = QtGui.QMenu(self.menuBar)
        self.menuX.setTitle(_fromUtf8(""))
        self.menuX.setObjectName(_fromUtf8("menuX"))
        self.menu_6 = QtGui.QMenu(self.menuBar)
        self.menu_6.setTitle(_fromUtf8(""))
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout_us = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_us.setIcon(icon2)
        self.actionAbout_us.setObjectName(_fromUtf8("actionAbout_us"))
        self.actionHow_to_use = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHow_to_use.setIcon(icon3)
        self.actionHow_to_use.setObjectName(_fromUtf8("actionHow_to_use"))
        self.actionContact = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icon/contact.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContact.setIcon(icon4)
        self.actionContact.setObjectName(_fromUtf8("actionContact"))
        self.actionS = QtGui.QAction(MainWindow)
        self.actionS.setObjectName(_fromUtf8("actionS"))
        self.menuHelp.addAction(self.actionAbout_us)
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuHelp.addAction(self.actionContact)
        self.menu_5.addAction(self.actionS)
        self.menuBar.addAction(self.menuBeltaGo.menuAction())
        self.menuBar.addAction(self.menuBgSerial.menuAction())
        self.menuBar.addAction(self.menuBgObjReg.menuAction())
        self.menuBar.addAction(self.menuBgVoice.menuAction())
        self.menuBar.addAction(self.menuBgGps.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.menuBar.addAction(self.menuX.menuAction())
        self.menuBar.addAction(self.menu_6.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BeltaGo", None))
        self.pushButton_9.setText(_translate("MainWindow", "power off", None))
        self.pushButton_6.setText(_translate("MainWindow", "L", None))
        self.pushButton_7.setText(_translate("MainWindow", "D", None))
        self.label_2.setText(_translate("MainWindow", "-", None))
        self.label_3.setText(_translate("MainWindow", "+", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:9pt;\"><br /></p></body></html>", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:9pt;\"><br /></p></body></html>", None))
        self.pushButton_5.setText(_translate("MainWindow", "R", None))
        self.pushButton_8.setText(_translate("MainWindow", "S", None))
        self.pushButton_4.setText(_translate("MainWindow", "U", None))
        self.label_5.setText(_translate("MainWindow", "Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "MainMenu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "taskMenu", None))
        self.label_6.setText(_translate("MainWindow", "x", None))
        self.label_13.setText(_translate("MainWindow", "y", None))
        self.label_16.setText(_translate("MainWindow", "z", None))
        self.pushButton_10.setText(_translate("MainWindow", "off", None))
        self.pushButton_11.setText(_translate("MainWindow", "catch", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "armMenu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "imageMenu", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "VoiceMenu", None))
        self.menuBeltaGo.setTitle(_translate("MainWindow", "BeltaGo", None))
        self.menuBgSerial.setTitle(_translate("MainWindow", "BgSerial", None))
        self.menuBgObjReg.setTitle(_translate("MainWindow", "BgObjReg", None))
        self.menuBgVoice.setTitle(_translate("MainWindow", "BgVoice", None))
        self.menuBgGps.setTitle(_translate("MainWindow", "BgGps", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menu_3.setTitle(_translate("MainWindow", "power", None))
        self.actionAbout_us.setText(_translate("MainWindow", "about us?", None))
        self.actionHow_to_use.setText(_translate("MainWindow", "how to use?", None))
        self.actionContact.setText(_translate("MainWindow", "contact?", None))
        self.actionS.setText(_translate("MainWindow", "s", None))

import img_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

